//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProgram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Вопрос> Вопросы { get; set; }
        public virtual DbSet<Группа> Группы { get; set; }
        public virtual DbSet<Ответ> Ответы { get; set; }
        public virtual DbSet<Раздел> Разделы { get; set; }
        public virtual DbSet<Результат> Результаты { get; set; }
        public virtual DbSet<Студент> Студенты { get; set; }
        public virtual DbSet<Студент_Результат> Студент_Результат { get; set; }
        public virtual DbSet<Тема> Темы { get; set; }
    }
}
