//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProgram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Вопрос> Вопрос { get; set; }
        public virtual DbSet<Группа> Группа { get; set; }
        public virtual DbSet<Ответ> Ответ { get; set; }
        public virtual DbSet<Раздел> Раздел { get; set; }
        public virtual DbSet<Результат> Результат { get; set; }
        public virtual DbSet<Студент> Студент { get; set; }
        public virtual DbSet<Тема> Тема { get; set; }
    }
}
