//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вопрос
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Вопрос()
        {
            this.Ответ = new HashSet<Ответ>();
        }
    
        public byte Id { get; set; }
        public string Текст { get; set; }
        public string Код { get; set; }
        public string Тип_Ответа { get; set; }
        public byte Раздел_Id { get; set; }
        public byte Тема_Id { get; set; }
    
        public virtual Раздел Раздел { get; set; }
        public virtual Тема Тема { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ответ> Ответ { get; set; }
    }
}
