//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ответ
    {
        public byte Id { get; set; }
        public string Текст { get; set; }
        public bool Значение { get; set; }
        public byte Вопрос_Id { get; set; }
    
        public virtual Вопрос Вопрос { get; set; }
    }
}
