//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Результат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Результат()
        {
            this.Студент_Результат = new HashSet<Студент_Результат>();
        }
    
        public byte Id { get; set; }
        public byte Оценка { get; set; }
        public System.DateTime Дата_Прохождения { get; set; }
        public byte Раздел_Название { get; set; }
        public byte Тема_Название { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студент_Результат> Студент_Результат { get; set; }
    }
}
