//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студент_Результат
    {
        public byte Id { get; set; }
        public byte Студент_Id { get; set; }
        public byte Результат_Id { get; set; }
    
        public virtual Результат Результат { get; set; }
        public virtual Студент Студент { get; set; }
    }
}
