//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тема
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тема()
        {
            this.Вопрос = new HashSet<Вопрос>();
        }
    
        public byte Id { get; set; }
        public string Название { get; set; }
        public byte Раздел_Id { get; set; }
        public System.TimeSpan Время_Прохождения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Вопрос> Вопрос { get; set; }
        public virtual Раздел Раздел { get; set; }
    }
}
